[supervisord]
nodaemon=true

[program:pocketbase]
command=./pocketbase serve --http=0.0.0.0:8090 --adminEmail=$PB_ADMIN_EMAIL --adminPassword=$PB_ADMIN_PASSWORD
autostart=true
autorestart=true
startretries=3

[program:bot]
command=python bible_bot.py
autostart=true
autorestart=true
startretries=3

