[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:pocketbase]
command=/opt/render/project/src/pocketbase serve --http=0.0.0.0:8090 --adminEmail=$PB_ADMIN_EMAIL --adminPassword=$PB_ADMIN_PASSWORD
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bot]
command=python bible_bot.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
